name: Audiora CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-api:
    name: Build & Test API
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codigo
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restaurar dependencias
        run: |
          dotnet restore src/Audiora.API/Audiora.API.csproj
          dotnet restore src/Audiora.Application/Audiora.Application.csproj
          dotnet restore src/Audiora.Domain/Audiora.Domain.csproj
          dotnet restore src/Audiora.Infrastructure/Audiora.Infrastructure.csproj

      - name: Build API
        run: dotnet build src/Audiora.API/Audiora.API.csproj --no-restore --configuration Release

  build-android:
    name: Build Android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codigo
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Build Android Debug
        run: |
          cd src/AudioraApp
          chmod +x gradlew
          ./gradlew assembleDebug --no-daemon
